<?php
require_once ('init.php');
require_once('models/user.php');
require_once('views/header.php');
?>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<h1 class="align-center"></h1>
<center>
<div class="card border-success mb-3 table" style="max-width: 24rem;">
  <div class="card-header bg-transparent border-success text-center">Smart BRs Ticket</div>
  <div class="card-body text-success">
    <h5 class="card-title text-danger">Ticket Route: Lahore To Gujranwala</h5>
    <h6>Name: Arslan Shahid</h6> 
    <h6>Seat No: 2,4</h6>
    <h6>Date: 20/10/2020</h6>
    <h6>Departure Time: 08:00 am</h6> 
    
  </div>
  <div class="card-footer bg-transparent border-success">Note: This Ticket is Generated by System Error May Be Expected</div>
  <input class="btn btn-success" value="Print Ticket" onClick="window.print()">
</div>

</center>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<?php
require_once('views/footer.php');
?>
